name: maimate_fixed
description: MVP for mAImate AI assistant.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Peruskirjastot
  intl: ^0.20.2
  cupertino_icons: ^1.0.6
  logger: ^2.0.2

  # Verkkoyhteydet
  http: ^1.2.1
  
  # Puhetekniikka
  speech_to_text: ^7.0.0
  flutter_tts: ^4.2.2
  
  # Firebase-paketit (yhteensopivat versiot)
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.6.7
  cloud_functions: ^5.5.0
  
  # Apukirjastot
  get_it: ^8.0.3
  url_launcher: ^6.2.5
  permission_handler: ^11.3.1
  translator: ^1.0.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/circuit_bg.png
