name: maimate_fixed
description: Älykäs elämänhallinta-assistentti
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  # Firebase
  firebase_core: ^2.10.0
  cloud_firestore: ^4.7.1
  firebase_auth: ^4.6.1
  firebase_storage: ^11.1.1

  # HTTP & NLP
  http: ^0.13.6

  # Ääniohjaus & puhesynteesi
  speech_to_text: ^6.3.0
  flutter_tts: ^3.6.3

  # Kalenteri
  table_calendar: ^3.0.9

  # Tilanhallinta
  provider: ^6.1.1

  # Lokalisointi
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/

