// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApkEwdlnRwHnTXxowea4zxEfYHNPxKbkk',
    appId: '1:78467677708:web:082d101254c28073f43829',
    messagingSenderId: '78467677708',
    projectId: 'maimate-7cc71',
    authDomain: 'maimate-7cc71.firebaseapp.com',
    storageBucket: 'maimate-7cc71.firebasestorage.app',
    measurementId: 'G-9TX1P9ZPEV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBC8Uo5ynx3mjQrp_INRSpLC5pR6Ac1EtI',
    appId: '1:78467677708:android:b90b22d78596b86af43829',
    messagingSenderId: '78467677708',
    projectId: 'maimate-7cc71',
    storageBucket: 'maimate-7cc71.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7wCx6f9t-zGynZaczijU5AEbwYCq0-Fk',
    appId: '1:78467677708:ios:629a1f8509137e8df43829',
    messagingSenderId: '78467677708',
    projectId: 'maimate-7cc71',
    storageBucket: 'maimate-7cc71.firebasestorage.app',
    iosBundleId: 'com.example.maimateMvp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7wCx6f9t-zGynZaczijU5AEbwYCq0-Fk',
    appId: '1:78467677708:ios:629a1f8509137e8df43829',
    messagingSenderId: '78467677708',
    projectId: 'maimate-7cc71',
    storageBucket: 'maimate-7cc71.firebasestorage.app',
    iosBundleId: 'com.example.maimateMvp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApkEwdlnRwHnTXxowea4zxEfYHNPxKbkk',
    appId: '1:78467677708:web:046577060f488b17f43829',
    messagingSenderId: '78467677708',
    projectId: 'maimate-7cc71',
    authDomain: 'maimate-7cc71.firebaseapp.com',
    storageBucket: 'maimate-7cc71.firebasestorage.app',
    measurementId: 'G-1Y4CJ5V2XN',
  );

}